import { Product, Order } from './types';

export function formatPrice(n: number): string {
  return '$' + n.toLocaleString('es-CO');
}

export const brands = [
  { id: 'royal-canin', name: 'Royal Canin' },
  { id: 'pro-plan', name: 'Pro Plan' },
  { id: 'hills', name: "Hill's" },
  { id: 'kong', name: 'KONG' },
  { id: 'zee-dog', name: 'Zee.Dog' },
  { id: 'catit', name: 'Catit' },
  { id: 'pedigree', name: 'Pedigree' },
  { id: 'whiskas', name: "Whiskas" },
];

export const products: Product[] = [
  {
    id: 'rc-med-adult',
    slug: 'royal-canin-medium-adult',
    name: 'Royal Canin Medium Adult',
    brand: 'Royal Canin',
    category: 'perros',
    subcategory: 'Alimento seco',
    description: 'Formulado específicamente para perros adultos de razas medianas (de 11 a 25 kg), Royal Canin Medium Adult ofrece nutrición precisa que ayuda a mantener el peso ideal, apoya la salud digestiva y protege la piel y el pelaje. Su fórmula avanzada contiene ácidos grasos omega-3 y omega-6 para una piel saludable y un pelaje brillante.',
    shortDesc: 'Nutrición precisa para razas medianas de 11 a 25 kg',
    images: [
      'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=600&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=600&fit=crop&auto=format',
    ],
    variants: [
      { id: 'v1', name: '4 lb', price: 45000, originalPrice: 52000, sku: 'RC-MED-4LB', stock: 15 },
      { id: 'v2', name: '10 lb', price: 95000, originalPrice: 110000, sku: 'RC-MED-10LB', stock: 8 },
      { id: 'v3', name: '14 lb', price: 125000, sku: 'RC-MED-14LB', stock: 12 },
      { id: 'v4', name: '25 lb', price: 195000, sku: 'RC-MED-25LB', stock: 5 },
    ],
    tags: ['mas-vendido', 'oferta'],
    active: true, featured: true, bestSeller: true,
  },
  {
    id: 'proplan-adult-chicken',
    slug: 'pro-plan-adult-chicken',
    name: 'Pro Plan Adult Chicken & Rice',
    brand: 'Pro Plan',
    category: 'perros',
    subcategory: 'Alimento seco',
    description: 'Pro Plan Adult con pollo y arroz proporciona nutrición avanzada con ingredientes de alta calidad para perros adultos activos. El pollo como primer ingrediente garantiza proteína de alta digestibilidad para mantener masa muscular magra.',
    shortDesc: 'Pollo real como primer ingrediente para energía activa',
    images: [
      'https://images.unsplash.com/photo-1568640347023-a616a30bc3bd?w=600&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=600&fit=crop&auto=format',
    ],
    variants: [
      { id: 'v1', name: '3 kg', price: 55000, sku: 'PP-ADT-3KG', stock: 20 },
      { id: 'v2', name: '7.5 kg', price: 110000, originalPrice: 125000, sku: 'PP-ADT-75KG', stock: 10 },
      { id: 'v3', name: '15 kg', price: 185000, sku: 'PP-ADT-15KG', stock: 7 },
    ],
    tags: ['mas-vendido'],
    active: true, featured: true, bestSeller: true,
  },
  {
    id: 'hills-adult',
    slug: 'hills-science-diet-adult',
    name: "Hill's Science Diet Adult",
    brand: "Hill's",
    category: 'perros',
    subcategory: 'Alimento seco',
    description: "Hill's Science Diet Adult es un alimento balanceado formulado por veterinarios para perros adultos sanos. Nutrición clínicamente probada con ingredientes naturales de calidad.",
    shortDesc: 'Formulado por veterinarios, nutrición clínicamente probada',
    images: [
      'https://images.unsplash.com/photo-1601758174114-e711c0cbaa69?w=600&h=600&fit=crop&auto=format',
    ],
    variants: [
      { id: 'v1', name: '3.5 lb', price: 48000, sku: 'HS-ADT-35LB', stock: 18 },
      { id: 'v2', name: '15 lb', price: 135000, originalPrice: 152000, sku: 'HS-ADT-15LB', stock: 9 },
    ],
    tags: ['oferta'],
    active: true, featured: false, bestSeller: false,
  },
  {
    id: 'rc-adult-cat',
    slug: 'royal-canin-adult-cat',
    name: 'Royal Canin Adult Cat',
    brand: 'Royal Canin',
    category: 'gatos',
    subcategory: 'Alimento seco',
    description: 'Alimento completo para gatos adultos de entre 1 y 7 años. Mantiene el peso ideal y apoya la salud del tracto urinario. Croquetas de tamaño y forma adaptados para la mandíbula del gato.',
    shortDesc: 'Equilibrio perfecto para gatos adultos 1-7 años',
    images: [
      'https://images.unsplash.com/photo-1548802673-380ab8ebc7b7?w=600&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=600&h=600&fit=crop&auto=format',
    ],
    variants: [
      { id: 'v1', name: '400 g', price: 28000, sku: 'RC-CAT-400G', stock: 25 },
      { id: 'v2', name: '2 kg', price: 75000, originalPrice: 88000, sku: 'RC-CAT-2KG', stock: 14 },
      { id: 'v3', name: '4 kg', price: 130000, sku: 'RC-CAT-4KG', stock: 8 },
    ],
    tags: ['mas-vendido', 'oferta'],
    active: true, featured: true, bestSeller: true,
  },
  {
    id: 'proplan-kitten',
    slug: 'pro-plan-kitten',
    name: 'Pro Plan Kitten Chicken',
    brand: 'Pro Plan',
    category: 'gatos',
    subcategory: 'Alimento seco',
    description: 'Nutrición de alta calidad para gatitos en crecimiento. Rico en DHA de aceite de pescado para el desarrollo cerebral y visual. El colostro bovino apoya el sistema inmunológico.',
    shortDesc: 'Fórmula rica en DHA para gatitos en crecimiento',
    images: [
      'https://images.unsplash.com/photo-1582725461742-8ecd962c260d?w=600&h=600&fit=crop&auto=format',
    ],
    variants: [
      { id: 'v1', name: '1.5 kg', price: 58000, sku: 'PP-KIT-15KG', stock: 16 },
      { id: 'v2', name: '3 kg', price: 98000, originalPrice: 110000, sku: 'PP-KIT-3KG', stock: 11 },
    ],
    tags: ['mas-vendido'],
    active: true, featured: true, bestSeller: true,
  },
  {
    id: 'kong-classic',
    slug: 'kong-classic',
    name: 'KONG Classic',
    brand: 'KONG',
    category: 'perros',
    subcategory: 'Juguetes',
    description: 'El juguete más icónico para perros. Fabricado en goma natural resistente, puedes rellenarlo con premios para estimulación mental y juego independiente. Ideal para masticadores entusiastas.',
    shortDesc: 'Juguete de goma clásico, rellénalo con premios',
    images: [
      'https://images.unsplash.com/photo-1601758174114-e711c0cbaa69?w=600&h=600&fit=crop&auto=format',
    ],
    variants: [
      { id: 'v1', name: 'S (0–9 kg)', price: 32000, sku: 'KONG-S', stock: 20 },
      { id: 'v2', name: 'M (9–16 kg)', price: 38000, sku: 'KONG-M', stock: 15 },
      { id: 'v3', name: 'L (16–29 kg)', price: 48000, originalPrice: 55000, sku: 'KONG-L', stock: 10 },
    ],
    tags: ['nuevo', 'oferta'],
    active: true, featured: false, bestSeller: false,
  },
  {
    id: 'zee-dog-collar',
    slug: 'zee-dog-collar-neo',
    name: 'Zee.Dog Collar Neo Dots',
    brand: 'Zee.Dog',
    category: 'accesorios',
    subcategory: 'Collares',
    description: 'Collar resistente y colorido de la colección Neo Dots. Tela de nylon premium con argolla de aluminio forjado. Diseño vibrante que se mantiene brillante con el uso.',
    shortDesc: 'Nylon premium, argolla de aluminio forjado',
    images: [
      'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=600&fit=crop&auto=format',
    ],
    variants: [
      { id: 'v1', name: 'XS', price: 45000, sku: 'ZD-COL-XS', stock: 8 },
      { id: 'v2', name: 'S', price: 50000, sku: 'ZD-COL-S', stock: 12 },
      { id: 'v3', name: 'M', price: 55000, sku: 'ZD-COL-M', stock: 10 },
      { id: 'v4', name: 'L', price: 60000, sku: 'ZD-COL-L', stock: 6 },
    ],
    tags: ['nuevo'],
    active: true, featured: false, bestSeller: false,
  },
  {
    id: 'catit-bebedero',
    slug: 'catit-bebedero-flower',
    name: 'Catit Bebedero Flower Fountain',
    brand: 'Catit',
    category: 'gatos',
    subcategory: 'Accesorios',
    description: 'Fuente de agua con filtro de triple acción que estimula a los gatos a beber más. Diseño en forma de flor con tres flujos diferentes para todos los gustos. Incluye filtro que elimina malos sabores.',
    shortDesc: 'Fuente con filtro triple para hidratación óptima',
    images: [
      'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=600&h=600&fit=crop&auto=format',
    ],
    variants: [
      { id: 'v1', name: '3 L', price: 89000, originalPrice: 105000, sku: 'CATIT-BEB-3L', stock: 7 },
    ],
    tags: ['oferta'],
    active: true, featured: true, bestSeller: false,
  },
];

export const orders: Order[] = [
  {
    id: 'ord-001',
    orderNumber: 'KW-2024-001',
    date: '2024-08-15',
    customer: {
      firstName: 'Valentina', lastName: 'Gómez',
      phone: '+57 310 234 5678', email: 'valentina@email.com',
      address: 'Calle 45 #23-12', neighborhood: 'El Poblado',
      city: 'Medellín', department: 'Antioquia',
    },
    items: [{
      productId: 'rc-med-adult', variantId: 'v2',
      productName: 'Royal Canin Medium Adult', brand: 'Royal Canin',
      variantName: '10 lb', price: 95000, quantity: 1,
      image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=80&h=80&fit=crop',
      slug: 'royal-canin-medium-adult',
    }],
    subtotal: 95000, discount: 0, shipping: 8000, total: 103000,
    paymentMethod: 'mercadopago', channel: 'tienda', status: 'entregado',
  },
  {
    id: 'ord-002',
    orderNumber: 'KW-2024-002',
    date: '2024-08-16',
    customer: {
      firstName: 'Andrés', lastName: 'Martínez',
      phone: '+57 315 987 6543', email: 'andres@email.com',
      address: 'Carrera 70 #10-45', neighborhood: 'Laureles',
      city: 'Medellín', department: 'Antioquia',
    },
    items: [{
      productId: 'rc-adult-cat', variantId: 'v2',
      productName: 'Royal Canin Adult Cat', brand: 'Royal Canin',
      variantName: '2 kg', price: 75000, quantity: 2,
      image: 'https://images.unsplash.com/photo-1548802673-380ab8ebc7b7?w=80&h=80&fit=crop',
      slug: 'royal-canin-adult-cat',
    }],
    subtotal: 150000, discount: 15000, discountReason: 'Descuento acordado por WhatsApp',
    shipping: 0, total: 135000,
    paymentMethod: 'contraentrega', channel: 'whatsapp', status: 'preparando',
  },
  {
    id: 'ord-003',
    orderNumber: 'KW-2024-003',
    date: '2024-08-17',
    customer: {
      firstName: 'Camila', lastName: 'Restrepo',
      phone: '+57 300 112 3344', email: 'camila@email.com',
      address: 'Avenida Las Vegas #52-36', neighborhood: 'Envigado',
      city: 'Medellín', department: 'Antioquia',
    },
    items: [{
      productId: 'proplan-adult-chicken', variantId: 'v2',
      productName: 'Pro Plan Adult Chicken & Rice', brand: 'Pro Plan',
      variantName: '7.5 kg', price: 110000, quantity: 1,
      image: 'https://images.unsplash.com/photo-1568640347023-a616a30bc3bd?w=80&h=80&fit=crop',
      slug: 'pro-plan-adult-chicken',
    }],
    subtotal: 110000, discount: 0, shipping: 8000, total: 118000,
    paymentMethod: 'mercadopago', channel: 'tienda', status: 'pendiente',
  },
  {
    id: 'ord-004',
    orderNumber: 'KW-2024-004',
    date: '2024-08-18',
    customer: {
      firstName: 'Santiago', lastName: 'López',
      phone: '+57 312 445 6789', email: 'santiago@email.com',
      address: 'Calle 33 Sur #43B-40', neighborhood: 'Sabaneta',
      city: 'Medellín', department: 'Antioquia',
    },
    items: [
      {
        productId: 'kong-classic', variantId: 'v2',
        productName: 'KONG Classic', brand: 'KONG',
        variantName: 'M (9–16 kg)', price: 38000, quantity: 1,
        image: 'https://images.unsplash.com/photo-1601758174114-e711c0cbaa69?w=80&h=80&fit=crop',
        slug: 'kong-classic',
      },
      {
        productId: 'zee-dog-collar', variantId: 'v3',
        productName: 'Zee.Dog Collar Neo Dots', brand: 'Zee.Dog',
        variantName: 'M', price: 55000, quantity: 1,
        image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=80&h=80&fit=crop',
        slug: 'zee-dog-collar-neo',
      },
    ],
    subtotal: 93000, discount: 0, shipping: 8000, total: 101000,
    paymentMethod: 'contraentrega', channel: 'manual', status: 'confirmado',
  },
  {
    id: 'ord-005',
    orderNumber: 'KW-2024-005',
    date: '2024-08-19',
    customer: {
      firstName: 'Isabella', lastName: 'Cardona',
      phone: '+57 321 678 9012', email: 'isabella@email.com',
      address: 'Calle 10 #43D-15', neighborhood: 'Florida Nueva',
      city: 'Medellín', department: 'Antioquia',
    },
    items: [{
      productId: 'proplan-kitten', variantId: 'v2',
      productName: 'Pro Plan Kitten Chicken', brand: 'Pro Plan',
      variantName: '3 kg', price: 98000, quantity: 1,
      image: 'https://images.unsplash.com/photo-1582725461742-8ecd962c260d?w=80&h=80&fit=crop',
      slug: 'pro-plan-kitten',
    }],
    subtotal: 98000, discount: 9800, discountReason: '10% descuento cliente frecuente',
    shipping: 8000, total: 96200,
    paymentMethod: 'mercadopago', channel: 'tienda', status: 'enviado',
  },
];
